// SPDX-License-Identifier: MIT
// Shared code-generation helpers

use crate::ast::{ImportKind, Statement};
use crate::global::{Options, MIG_VERSION};
use std::io::{self, Write};

pub fn write_identification(w: &mut dyn Write, opts: &Options) -> io::Result<()> {
    writeln!(w, "/*")?;
    writeln!(w, " * IDENTIFICATION:")?;
    writeln!(w, " * stub generated by {MIG_VERSION}")?;
    writeln!(w, " * OPTIONS:")?;
    if opts.is_kernel_user {
        writeln!(w, " *\tKernelUser")?;
    }
    if opts.is_kernel_server {
        writeln!(w, " *\tKernelServer")?;
    }
    if !opts.use_msg_rpc {
        writeln!(w, " *\t-R (no RPC calls)")?;
    }
    writeln!(w, " */")
}

pub fn write_mig_external(w: &mut dyn Write) -> io::Result<()> {
    writeln!(w, "#ifdef\tmig_external")?;
    writeln!(w, "mig_external")?;
    writeln!(w, "#else")?;
    writeln!(w, "extern")?;
    writeln!(w, "#endif\t/* mig_external */")
}

#[allow(dead_code)]
pub fn write_mig_internal(w: &mut dyn Write) -> io::Result<()> {
    writeln!(w, "#ifdef\tmig_internal")?;
    writeln!(w, "mig_internal")?;
    writeln!(w, "#else")?;
    writeln!(w, "static")?;
    writeln!(w, "#endif\t/* mig_internal */")
}

/// Emit `#include` lines for import statements of the requested kinds.
pub fn write_imports(
    w: &mut dyn Write,
    stmts: &[Statement],
    kinds: &[ImportKind],
) -> io::Result<()> {
    for stmt in stmts {
        if let Statement::Import { kind, filename } = stmt {
            if kinds.contains(kind) {
                writeln!(w, "#include {filename}")?;
            }
        }
    }
    Ok(())
}
