// CodeGenUtils.swift — Shared code generation utilities

import Foundation

// MARK: - Output file helpers

class IndentWriter {
  let stream: FileHandle
  var indentLevel = 0

  init(stream: FileHandle) {
    self.stream = stream
  }

  func write(_ s: String) {
    let indented = String(repeating: "\t", count: indentLevel) + s
    stream.write(Data(indented.utf8))
  }

  func writeln(_ s: String = "") {
    write(s + "\n")
  }

  func indent() { indentLevel += 1 }
  func outdent() { indentLevel = max(0, indentLevel - 1) }

  func blankLine() { writeln() }
}

// MARK: - File open helpers

func openWriteHandle(_ name: String) -> FileHandle? {
  if name.isEmpty || name == "/dev/null" { return nil }
  let url = URL(fileURLWithPath: name)

  if !FileManager.default.fileExists(atPath: name) {
    _ = FileManager.default.createFile(atPath: name, contents: nil)
  }

  return try? FileHandle(forWritingTo: url)
}

func openIndentWriter(_ name: String) -> IndentWriter? {
  if name.isEmpty || name == "/dev/null" { return nil }
  guard let handle = FileHandle(forWritingAtPath: name) else {
    // Try creating
    _ = FileManager.default.createFile(atPath: name, contents: nil)
    guard let h = FileHandle(forWritingAtPath: name) else {
      fatal("openOutputFile: cannot write to \(name)")
    }
    return IndentWriter(stream: h)
  }
  handle.truncateFile(atOffset: 0)
  return IndentWriter(stream: handle)
}

func writeFile(_ name: String, content: String) {
  do {
    try content.write(toFile: name, atomically: true, encoding: .utf8)
  } catch {
    fatal("Cannot write to \(name): \(error)")
  }
}

// MARK: - Writer functions

func writeIdentificationString(_ w: IndentWriter) {
  w.writeln("/*")
  w.writeln(" * IDENTIFICATION:")
  w.writeln(" * stub generated by \(Global.MIG_VERSION)")
  w.writeln(" * OPTIONS: ")
  if Global.isKernelUser { w.writeln(" *\tKernelUser") }
  if Global.isKernelServer { w.writeln(" *\tKernelServer") }
  if !Global.useMsgRPC { w.writeln(" *\t-R (no RPC calls)") }
  w.writeln(" */")
}

func writeBogusDefines(_ w: IndentWriter) {
  w.writeln("#ifndef\tmig_internal")
  w.writeln("#define\tmig_internal\tstatic __inline__")
  w.writeln("#endif\t/* mig_internal */")
  w.blankLine()
  w.writeln("#ifndef\tmig_external")
  w.writeln("#define mig_external")
  w.writeln("#endif\t/* mig_external */")
  w.blankLine()
  w.writeln("#if\t!defined(__MigTypeCheck) && defined(TypeCheck)")
  w.writeln("#define\t__MigTypeCheck\t\tTypeCheck\t/* Legacy setting */")
  w.writeln("#endif\t/* !defined(__MigTypeCheck) */")
  w.blankLine()
  w.writeln("#if\t!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)")
  w.writeln("#define\t__MigKernelSpecificCode\t_MIG_KERNEL_SPECIFIC_CODE_\t/* Legacy setting */")
  w.writeln("#endif\t/* !defined(__MigKernelSpecificCode) */")
  w.blankLine()
  w.writeln("#ifndef\tLimitCheck")
  w.writeln("#define\tLimitCheck 0")
  w.writeln("#endif\t/* LimitCheck */")
  w.blankLine()
  w.writeln("#ifndef\tmin")
  w.writeln("#define\tmin(a,b)  ( ((a) < (b))? (a): (b) )")
  w.writeln("#endif\t/* min */")
  w.blankLine()

  let align = Int(itWordAlign)
  w.writeln("#if !defined(_WALIGN_)")
  w.writeln("#define _WALIGN_(x) (((x) + \(align - 1)) & ~\(align - 1))")
  w.writeln("#endif /* !defined(_WALIGN_) */")
  w.blankLine()
  w.writeln("#if !defined(_WALIGNSZ_)")
  w.writeln("#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))")
  w.writeln("#endif /* !defined(_WALIGNSZ_) */")
  w.blankLine()
  w.writeln("#ifndef\tUseStaticTemplates")
  if Global.beAnsiC {
    w.writeln("#define\tUseStaticTemplates\t0")
  } else {
    w.writeln("#if\t\(Global.newCDecl)")
    w.writeln("#define\tUseStaticTemplates\t0")
    w.writeln("#endif\t/* \(Global.newCDecl) */")
  }
  w.writeln("#endif\t/* UseStaticTemplates */")
  w.blankLine()
}

func writeImport(_ w: IndentWriter, filename: String) {
  w.writeln("#include \(filename)")
}

func writeImplImports(_ w: IndentWriter, statements: [Statement], isUser: Bool) {
  for st in statements {
    switch st.stKind {
    case .import_, .iImport:
      writeImport(w, filename: st.stFileName)
    case .sImport:
      if !isUser {
        writeImport(w, filename: st.stFileName)
      }
    case .uImport:
      if isUser {
        writeImport(w, filename: st.stFileName)
      }
    case .routine, .dImport:
      break
    default: break
    }
  }
}

func writeRCSDecl(_ w: IndentWriter, name: String, rcs: String) {
  let const = Global.beAnsiC ? "const " : ""
  w.writeln("#ifndef\tlint")
  w.writeln("#if\tUseExternRCSId")
  w.writeln("\(const)char \(name)_rcsid[] = \(rcs);")
  w.writeln("#else\t/* UseExternRCSId */")
  w.writeln("static \(const)char rcsid[] = \(rcs);")
  w.writeln("#endif\t/* UseExternRCSId */")
  w.writeln("#endif\t/* lint */")
  w.blankLine()
}

func fetchUserType(_ it: IPCType) -> String { it.itUserType }
func fetchServerType(_ it: IPCType) -> String { it.itServerType }

func returnTypeStr(_ rt: Routine) -> String {
  return rt.rtRetCode?.argType?.itUserType ?? "kern_return_t"
}

// MARK: - WriteList helpers

func writeList(
  _ w: IndentWriter, args: Argument?,
  fn: (IndentWriter, Argument) -> Void,
  mask: UInt, between: String, after: String
) {
  var arg = args
  var sawOne = false
  while let a = arg {
    if akCheckAll(a.argKind, mask) {
      if sawOne { w.write(between) }
      sawOne = true
      fn(w, a)
    }
    arg = a.argNext
  }
  if sawOne { w.write(after) }
}

func writeReverseList(
  _ w: IndentWriter, args: Argument?,
  fn: (IndentWriter, Argument) -> Void,
  mask: UInt, between: String, after: String
) {
  var list: [Argument] = []
  var arg = args
  while let a = arg {
    if akCheckAll(a.argKind, mask) {
      list.append(a)
    }
    arg = a.argNext
  }
  if !list.isEmpty {
    for i in 0..<list.count {
      let idx = list.count - 1 - i
      if i > 0 { w.write(between) }
      fn(w, list[idx])
    }
    w.write(after)
  }
}

func writeNameDecl(_ w: IndentWriter, arg: Argument) {
  w.write(arg.argVarName)
}

func writeFieldDeclPrim(_ w: IndentWriter, arg: Argument, tfunc: (IPCType) -> String) {
  guard let it = arg.argType else { return }

  if it.isVariableSizedUntyped || it.itNoOptArray {
    let count = arg.argCount
    let btype = it.itElement

    if it.itString {
      w.writeln("\t\t\(tfunc(count!.argType!)) \(arg.argName)Offset; /* MIG doesn't use it */")
    }

    if !arg.argFlags.contains(.sameCount) && !it.itNoOptArray {
      w.writeln("\t\t\(tfunc(count!.argType!)) \(count!.argMsgField);")
    }
    if let bt = btype {
      let elemCount = it.itNumber / bt.itNumber
      w.writeln("\t\t\(tfunc(bt)) \(arg.argMsgField)[\(elemCount)];")
    }
  } else if it.isMultipleKPD {
    w.writeln("\t\t\(tfunc(it)) \(arg.argMsgField)[\(it.itKPD_Number)];")
  } else if it.isOptionalNative {
    w.writeln("\t\tboolean_t __Present__\(arg.argMsgField);")
    w.writeln("\t\tunion {")
    w.writeln("\t\t    \(tfunc(it)) __Real__\(arg.argMsgField);")
    w.writeln("\t\t    char __Phony__\(arg.argMsgField)[_WALIGNSZ_(\(tfunc(it)))];")
    w.writeln("\t\t} \(arg.argMsgField);")
  } else {
    w.writeln("\t\t\(tfunc(it)) \(arg.argMsgField);")
  }

  if it.itPadSize != 0 {
    w.writeln("\n\t\tchar \(arg.argPadName)[\(it.itPadSize)];")
  }
}

func writeKPDFieldDecl(_ w: IndentWriter, arg: Argument) {
  if akCheck(arg.argKind, akbSendKPD) || akCheck(arg.argKind, akbReturnKPD) {
    writeFieldDeclPrim(w, arg: arg, tfunc: { $0.itKPDType })
  } else {
    writeFieldDeclPrim(w, arg: arg, tfunc: fetchServerType)
  }
}

// MARK: - Struct declarations for request/reply

func writeStructDecl(
  _ w: IndentWriter, args: Argument?,
  fieldWriter: @escaping (IndentWriter, Argument) -> Void,
  mask: UInt, name: String,
  simple: Bool, trailer: Bool, trailerT: Bool,
  templateOnly: Bool
) {
  let padding = UInt(MemoryLayout<Int>.stride)
  w.blankLine()
  w.writeln("#ifdef  __MigPackStructs")
  w.writeln("#pragma pack(push, \(padding))")
  w.writeln("#endif")
  w.writeln("\ttypedef struct {")
  w.writeln("\t\tmach_msg_header_t Head;")

  if !simple {
    w.writeln("\t\t/* start of the kernel processed data */")
    w.writeln("\t\tmach_msg_body_t msgh_body;")
    if mask == akbRequest {
      writeList(w, args: args, fn: fieldWriter, mask: mask | akbSendKPD, between: "\n", after: "\n")
    } else {
      writeList(
        w, args: args, fn: fieldWriter, mask: mask | akbReturnKPD, between: "\n", after: "\n")
    }
    w.writeln("\t\t/* end of the kernel processed data */")
  }

  if !templateOnly {
    if mask == akbRequest {
      writeList(
        w, args: args, fn: fieldWriter, mask: mask | akbSendBody, between: "\n", after: "\n")
    } else {
      writeList(
        w, args: args, fn: fieldWriter, mask: mask | akbReturnBody, between: "\n", after: "\n")
    }
    if trailer {
      if trailerT {
        w.writeln("\t\tmach_msg_max_trailer_t trailer;")
      } else {
        w.writeln("\t\tmach_msg_trailer_t trailer;")
      }
    }
  }

  w.writeln("\t} \(name) __attribute__((unused));")
  w.writeln("#ifdef  __MigPackStructs")
  w.writeln("#pragma pack(pop)")
  w.writeln("#endif")
}

func writeRequestTypes(_ w: IndentWriter, statements: [Statement]) {
  w.writeln("/* typedefs for all requests */")
  w.blankLine()
  w.writeln("#ifndef __Request__\(Global.subsystemName)_subsystem__defined")
  w.writeln("#define __Request__\(Global.subsystemName)_subsystem__defined")

  for st in statements {
    if st.stKind == .routine, let rt = st.stRoutine {
      let name = "__Request__\(rt.rtName)_t"
      writeStructDecl(
        w, args: rt.rtArgs, fieldWriter: writeKPDFieldDecl,
        mask: akbRequest, name: name,
        simple: rt.rtSimpleRequest, trailer: false, trailerT: false,
        templateOnly: false)
    }
  }

  w.writeln("#endif /* !__Request__\(Global.subsystemName)_subsystem__defined */")
  w.blankLine()
}

func writeReplyTypes(_ w: IndentWriter, statements: [Statement]) {
  w.writeln("/* typedefs for all replies */")
  w.blankLine()
  w.writeln("#ifndef __Reply__\(Global.subsystemName)_subsystem__defined")
  w.writeln("#define __Reply__\(Global.subsystemName)_subsystem__defined")

  for st in statements {
    if st.stKind == .routine, let rt = st.stRoutine {
      let name = "__Reply__\(rt.rtName)_t"
      writeStructDecl(
        w, args: rt.rtArgs, fieldWriter: writeKPDFieldDecl,
        mask: akbReply, name: name,
        simple: rt.rtSimpleReply, trailer: false, trailerT: false,
        templateOnly: false)
    }
  }

  w.writeln("#endif /* !__Reply__\(Global.subsystemName)_subsystem__defined */")
  w.blankLine()
}

// MARK: - User/Server var decl

func getUserArgStar(_ arg: Argument) -> String {
  if arg.argType?.itNativePointer ?? false { return "*" }
  if arg.argByReferenceUser { return "*" }
  return ""
}

func getServerArgStar(_ arg: Argument) -> String {
  if arg.argType?.itNativePointer ?? false { return "*" }
  if arg.argByReferenceServer { return "*" }
  return ""
}

func getConstPrefix(_ arg: Argument) -> String {
  guard let t = arg.argType else { return "" }
  if arg.argFlags.contains(.constFlag) && (t.isVariableSizedUntyped || t.itNoOptArray || t.itString)
  {
    return "const "
  }
  return ""
}

func writeUserVarDecl(_ w: IndentWriter, arg: Argument) {
  guard let t = arg.argType else { return }
  w.write("\t\(getConstPrefix(arg))\(t.itUserType) \(getUserArgStar(arg))\(arg.argVarName)")
}

func writeServerVarDecl(_ w: IndentWriter, arg: Argument) {
  guard let t = arg.argType else { return }
  w.write("\t\(getConstPrefix(arg))\(t.itTransType) \(getServerArgStar(arg))\(arg.argVarName)")
}

// MARK: - Copy operations

func writeCopyType(_ w: IndentWriter, it: IPCType, left: String, right: String) {
  if it.itStruct {
    w.writeln("\t\(left) = \(right);")
  } else if it.itString {
    w.writeln("\t(void) mig_strncpy(\(left), \(right), \(it.itTypeSize));")
  } else {
    w.writeln("\t{ typedef struct { char data[\(it.itTypeSize)]; } *sp;")
    w.writeln("\t    * (sp) \(left) = * (sp) \(right);")
    w.writeln("\t}")
  }
}

func writeCopyArg(_ w: IndentWriter, arg: Argument, left: String, right: String) {
  guard let it = arg.argType else { return }
  if it.itVarArray && !it.itString, let count = arg.argCount {
    w.writeln("\t    (void)memcpy(\(left), \(right), \(count.argVarName));")
  } else {
    writeCopyType(w, it: it, left: left, right: right)
  }
}

// MARK: - Error return

let MIG_TYPE_ERROR = -300
let MIG_REPLY_MISMATCH = -301
let MIG_REMOTE_ERROR = -302
let MIG_BAD_ID = -303
let MIG_BAD_ARGUMENTS = -304
let MIG_NO_REPLY = -305
let MIG_EXCEPTION = -306
let MIG_ARRAY_TOO_LARGE = -307
let MIG_TRAILER_ERROR = -308

func writeReturnMsgError(_ w: IndentWriter, rt: Routine, isUser: Bool, errorCode: String) {
  w.writeln("\t\t{ ")
  if isUser {
    if !rtMessOnStack(rt) {
      w.writeln("\t\tmig_user_deallocate((char *) Mess, (mach_msg_size_t)sizeof(*Mess));")
    }
    w.writeln("\t\treturn \(errorCode); }")
  } else {
    w.writeln("\t\t{ MIG_RETURN_ERROR(OutP, \(errorCode)); }")
  }
}
