// ServerWriter.swift — Generate server-side stub code

import Foundation

func writeServer(fileName: String, statements: [Statement]) {
  var w = AccumWriter()
  writeServerProlog(&w, statements: statements)

  // Demux function
  writeServerDemux(&w, statements: statements)

  // Individual server routines
  for st in statements {
    if st.stKind == .routine, let rt = st.stRoutine {
      writeServerRoutine(&w, rt: rt)
    }
  }

  do {
    try w.output.write(toFile: fileName, atomically: true, encoding: .utf8)
  } catch {
    fatal("Cannot write to \(fileName): \(error)")
  }
}

private func writeServerProlog(_ w: inout AccumWriter, statements: [Statement]) {
  w.writeln("/*")
  w.writeln(" * IDENTIFICATION:")
  w.writeln(" * stub generated by \(Global.MIG_VERSION)")
  w.writeln(" * OPTIONS:")
  if Global.isKernelUser { w.writeln(" *\tKernelUser") }
  if Global.isKernelServer { w.writeln(" *\tKernelServer") }
  w.writeln(" */")
  w.blankLine()

  if Global.emitCountAnnotations {
    w.writeln("#include <sys/cdefs.h>")
  }
  w.writeln("#include <string.h>")
  w.writeln("#include <mach/ndr.h>")
  w.writeln("#include <mach/boolean.h>")
  w.writeln("#include <mach/kern_return.h>")
  w.writeln("#include <mach/notify.h>")
  w.writeln("#include <mach/mach_types.h>")
  w.writeln("#include <mach/message.h>")
  w.writeln("#include <mach/mig_errors.h>")
  w.writeln("#include <mach/port.h>")

  if !Global.userHeaderFileName.isEmpty {
    w.writeln("#include \"\(Global.userHeaderFileName)\"")
  }
  if !Global.serverHeaderFileName.isEmpty {
    w.writeln("#include \"\(Global.serverHeaderFileName)\"")
  } else {
    // Include user header for function declarations
    w.writeln("#include \"\(Global.userHeaderFileName)\"")
  }
  w.blankLine()

  // Write bogus defines
  let align = Int(itWordAlign)
  w.writeln("#ifndef\tmig_internal")
  w.writeln("#define\tmig_internal\tstatic __inline__")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#ifndef\tmig_external")
  w.writeln("#define mig_external")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#if !defined(_WALIGN_)")
  w.writeln("#define _WALIGN_(x) (((x) + \(align - 1)) & ~\(align - 1))")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#ifndef\tmig_strncpy")
  w.writeln("#define\tmig_strncpy\tstrncpy")
  w.writeln("#endif")
  w.blankLine()

  // MIG_RETURN_ERROR macro
  w.writeln("#ifndef MIG_RETURN_ERROR")
  w.writeln("#define MIG_RETURN_ERROR(OutP, code) \\")
  w.writeln("\t{ OutP->Head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0); \\")
  w.writeln("\t  OutP->Head.msgh_remote_port = In0P->Head.msgh_reply_port; \\")
  w.writeln("\t  OutP->Head.msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t); \\")
  w.writeln("\t  OutP->Head.msgh_local_port = MACH_PORT_NULL; \\")
  w.writeln("\t  OutP->Head.msgh_id = In0P->Head.msgh_id + 100; \\")
  w.writeln("\t  OutP->NDR = NDR_record; \\")
  w.writeln("\t  OutP->RetCode = code; \\")
  w.writeln("\t  return; }")
  w.writeln("#endif")
  w.blankLine()
}

private func writeServerDemux(_ w: inout AccumWriter, statements: [Statement]) {
  let routineStatements = statements.filter { $0.stKind == .routine }
  let count = routineStatements.count

  w.writeln(
    "mig_external boolean_t \(Global.serverDemux)(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)"
  )
  w.writeln("{")

  // Declare In/Out pointer types
  w.writeln("\ttypeof(InHeadP) In0P = InHeadP;")
  w.writeln("\ttypeof(OutHeadP) OutP = OutHeadP;")
  w.blankLine()

  w.writeln("\tint msgh_id = In0P->msgh_id;")
  w.blankLine()

  if count > 0 {
    w.writeln(
      "\tif ((msgh_id >= \(Global.subsystemBase)) && (msgh_id <= \(Global.subsystemBase + UInt(count - 1)))) {"
    )
    w.writeln("\t\tswitch (msgh_id) {")

    for st in routineStatements {
      guard let rt = st.stRoutine else { continue }
      let id = Global.subsystemBase + rt.rtNumber
      let serverName = Global.serverPrefix.isEmpty ? rt.rtName : Global.serverPrefix + rt.rtName
      w.writeln("\t\tcase \(id):")
      w.writeln("\t\t{")
      w.writeln("\t\t\t\(serverName)(InHeadP, OutHeadP);")
      w.writeln("\t\t\treturn TRUE;")
      w.writeln("\t\t}")
    }

    w.writeln("\t\tdefault:")
    w.writeln("\t\t\tbreak;")
    w.writeln("\t\t}")
    w.writeln("\t}")
  }

  // Not found
  w.writeln("\tOutP->Head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);")
  w.writeln("\tOutP->Head.msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);")
  w.writeln("\tOutP->Head.msgh_remote_port = In0P->Head.msgh_reply_port;")
  w.writeln("\tOutP->Head.msgh_local_port = MACH_PORT_NULL;")
  w.writeln("\tOutP->Head.msgh_id = In0P->Head.msgh_id + 100;")
  w.writeln("\t((mig_reply_error_t *)OutP)->NDR = NDR_record;")
  w.writeln("\t((mig_reply_error_t *)OutP)->RetCode = MIG_BAD_ID;")
  w.writeln("\treturn FALSE;")
  w.writeln("}")
  w.blankLine()
}

private func writeServerRoutine(_ w: inout AccumWriter, rt: Routine) {
  let serverName = Global.serverPrefix.isEmpty ? rt.rtName : Global.serverPrefix + rt.rtName

  // We need to generate a function that:
  // 1. Takes InHeadP and OutHeadP (generic pointers)
  // 2. Casts them to typed pointers
  // 3. Extracts request arguments
  // 4. Calls the actual server function
  // 5. Builds the reply

  w.writeln("/* Routine \(rt.rtName) */")
  w.writeln(
    "mig_internal void \(serverName)(mach_msg_header_t *_InHeadP, mach_msg_header_t *_OutHeadP)")
  w.writeln("{")

  // Typed declarations
  w.writeln("\t__Request__\(rt.rtName)_t *In0P = (__Request__\(rt.rtName)_t *)_InHeadP;")
  w.writeln("\t__Reply__\(rt.rtName)_t *OutP = (__Reply__\(rt.rtName)_t *)_OutHeadP;")
  w.blankLine()

  // Declare local variables for in arguments
  var arg = rt.rtArgs
  while let a = arg {
    guard let t = a.argType else {
      arg = a.argNext
      continue
    }
    if akCheck(a.argKind, akbServerArg) && akCheck(a.argKind, akbSendRcv)
      && akCheck(a.argKind, akbSendBody)
    {
      let star = t.itNativePointer ? "*" : ""
      w.writeln("\t\(t.itTransType) \(star)\(a.argVarName);")
    }
    arg = a.argNext
  }

  // Declare out variables (pointers from the message)
  arg = rt.rtArgs
  while let a = arg {
    guard let t = a.argType else {
      arg = a.argNext
      continue
    }
    if akCheck(a.argKind, akbServerArg) && akCheck(a.argKind, akbReturnSnd)
      && akCheck(a.argKind, akbReturnBody)
    {
      w.writeln("\t\(t.itTransType) *\(a.argVarName) = &OutP->\(a.argMsgField);")
    }
    arg = a.argNext
  }

  w.blankLine()

  // Extract request values (copy from message to local vars)
  arg = rt.rtArgs
  while let a = arg {
    guard let t = a.argType else {
      arg = a.argNext
      continue
    }
    if akCheck(a.argKind, akbServerArg) && akCheck(a.argKind, akbSendRcv)
      && akCheck(a.argKind, akbSendBody)
    {
      if t.itString {
        w.writeln("\t(void) mig_strncpy(\(a.argVarName), In0P->\(a.argMsgField), \(t.itTypeSize));")
      } else if t.itStruct && t.itNumber == 1 {
        w.writeln("\t\(a.argVarName) = In0P->\(a.argMsgField);")
      }
    }
    arg = a.argNext
  }
  w.blankLine()

  // Initialize reply header
  w.writeln("\tOutP->Head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);")
  w.writeln("\tOutP->Head.msgh_size = (mach_msg_size_t)sizeof(__Reply__\(rt.rtName)_t);")
  w.writeln("\tOutP->Head.msgh_remote_port = In0P->Head.msgh_reply_port;")
  w.writeln("\tOutP->Head.msgh_local_port = MACH_PORT_NULL;")
  w.writeln("\tOutP->Head.msgh_id = In0P->Head.msgh_id + 100;")
  w.blankLine()

  if !rt.rtSimpleReply {
    w.writeln("\tOutP->msgh_body.msgh_descriptor_count = \(rt.rtReplyKPDs);")
  }
  w.blankLine()

  // Call the actual server function
  w.write("\tOutP->RetCode = \(serverName)(")

  var firstArg = true
  arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbServerArg) {
      if !firstArg { w.write(", ") }
      firstArg = false
      w.write(a.argVarName)
    }
    arg = a.argNext
  }

  w.writeln(");")
  w.writeln("}")
  w.blankLine()
}

// For kernel servers, include the implementation structure
func writeServerImplementation(_ w: inout AccumWriter, statements: [Statement]) {
  let routineStatements = statements.filter { $0.stKind == .routine }
  let count = routineStatements.count

  w.writeln("const struct \(Global.serverSubsys) \(Global.serverSubsys) = {")
  w.writeln("\t\(Global.subsystemBase),")
  w.writeln("\t\(Global.subsystemBase + UInt(count)),")
  w.writeln("\t\(Global.serverDemux)")
  w.writeln("};")
  w.blankLine()
}
