// UserWriter.swift — Generate user-side stub code

import Foundation

func writeUser(fileName: String, statements: [Statement]) {
  var w = AccumWriter()
  writeUserProlog(&w, statements: statements)

  for st in statements {
    if st.stKind == .routine, let rt = st.stRoutine {
      if rt.rtOneWay {
        writeUserSimpleRoutine(&w, rt: rt)
      } else {
        writeUserRoutine(&w, rt: rt)
      }
    }
  }

  // Write to file
  do {
    try w.output.write(toFile: fileName, atomically: true, encoding: .utf8)
  } catch {
    fatal("Cannot write to \(fileName): \(error)")
  }
}

// AccumWriter accumulates output into a string
struct AccumWriter {
  var output = ""

  mutating func write(_ s: String) { output += s }
  mutating func writeln(_ s: String = "") { output += s + "\n" }
  mutating func blankLine() { writeln() }

  func indentStr(_ level: Int) -> String {
    String(repeating: "\t", count: level)
  }

  mutating func indent(_ level: Int = 1) {
    // Not really needed for accumulator - just write with tabs
  }

  mutating func writeIndented(_ s: String, level: Int = 0) {
    output += indentStr(level) + s
  }
  mutating func writelnIndented(_ s: String, level: Int = 0) {
    output += indentStr(level) + s + "\n"
  }
}

private func writeUserProlog(_ w: inout AccumWriter, statements: [Statement]) {
  w.writeln("/*")
  w.writeln(" * IDENTIFICATION:")
  w.writeln(" * stub generated by \(Global.MIG_VERSION)")
  w.writeln(" */")
  w.blankLine()

  if Global.emitCountAnnotations {
    w.writeln("#include <sys/cdefs.h>")
  }
  w.writeln("#include <string.h>")
  w.writeln("#include <mach/ndr.h>")
  w.writeln("#include <mach/boolean.h>")
  w.writeln("#include <mach/kern_return.h>")
  w.writeln("#include <mach/notify.h>")
  w.writeln("#include <mach/mach_types.h>")
  w.writeln("#include <mach/message.h>")
  w.writeln("#include <mach/mig_errors.h>")
  w.writeln("#include <mach/port.h>")

  if !Global.userHeaderFileName.isEmpty {
    w.writeln("#include \"\(Global.userHeaderFileName)\"")
  }
  w.blankLine()

  writeBogusDefines(&w)
  writeUserDefines(&w)
}

private func writeBogusDefines(_ w: inout AccumWriter) {
  let align = Int(itWordAlign)
  w.writeln("#ifndef\tmig_internal")
  w.writeln("#define\tmig_internal\tstatic __inline__")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#ifndef\tmig_external")
  w.writeln("#define mig_external")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#if !defined(_WALIGN_)")
  w.writeln("#define _WALIGN_(x) (((x) + \(align - 1)) & ~\(align - 1))")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#if !defined(_WALIGNSZ_)")
  w.writeln("#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))")
  w.writeln("#endif")
  w.blankLine()
}

private func writeUserDefines(_ w: inout AccumWriter) {
  w.writeln("#ifndef\tmig_strncpy")
  w.writeln("#define\tmig_strncpy\tstrncpy")
  w.writeln("#endif")
  w.blankLine()
  w.writeln("#ifdef mig_user_allocate")
  w.writeln("#define mig_user_allocate(S)\t(mach_msg_size_t)(S)")
  w.writeln("#endif")
  w.writeln("#ifdef mig_user_deallocate")
  w.writeln("#define mig_user_deallocate(P,S)\t((void)0)")
  w.writeln("#endif")
  w.blankLine()
}

private func writeUserRoutine(_ w: inout AccumWriter, rt: Routine) {
  let userName = Global.userPrefix.isEmpty ? rt.rtName : Global.userPrefix + rt.rtName
  let retType = returnTypeStr(rt)

  w.writeln("/* Routine \(rt.rtName) */")
  w.write("mig_external \(retType) \(userName)\n(")

  // Parameters
  var first = true
  var arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbUserArg) {
      if !first { w.write(",\n") }
      first = false
      let star = (a.argType?.itNativePointer ?? false) ? "*" : ""
      w.write("\t\(a.argType?.itUserType ?? "void") \(star)\(a.argVarName)")
    }
    arg = a.argNext
  }
  if first { w.write("\tvoid") }
  w.writeln(")")
  w.writeln("{")

  // Local vars
  w.writeln("\tunion {")
  w.writeln("\t\t__Request__\(rt.rtName)_t In;")
  w.writeln("\t\t__Reply__\(rt.rtName)_t Out;")
  w.writeln("\t} Mess;")
  w.writeln(
    "\tmach_port_t msgh_request_port = \(rt.rtRequestPort?.argVarName ?? "MACH_PORT_NULL");")
  w.writeln("\tmach_port_t msgh_reply_port = MACH_PORT_NULL;")
  w.blankLine()

  // Initialize request message
  w.writeln("\tmach_msg_return_t msg_result;")
  w.blankLine()
  w.writeln("\t(void) memset(&Mess, 0, sizeof(Mess));")
  w.blankLine()

  // Set up message header
  w.writeln(
    "\tMess.In.Head.msgh_bits = MACH_MSGH_BITS(19/*MACH_MSG_TYPE_COPY_SEND*/, MACH_MSG_TYPE_MAKE_SEND_ONCE);"
  )
  w.writeln("\tMess.In.Head.msgh_remote_port = msgh_request_port;")
  w.writeln("\tMess.In.Head.msgh_reply_port = mig_get_reply_port();")
  w.writeln("\tMess.In.Head.msgh_size = (mach_msg_size_t)sizeof(__Request__\(rt.rtName)_t);")
  w.writeln("\tMess.In.Head.msgh_id = \(Global.subsystemBase + rt.rtNumber);")
  w.blankLine()

  if !rt.rtSimpleRequest {
    w.writeln("\tMess.In.msgh_body.msgh_descriptor_count = \(rt.rtRequestKPDs);")
  }

  // Fill in request args
  arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbSendSnd) && akCheck(a.argKind, akbSendBody) {
      if let t = a.argType, t.itString {
        w.writeln(
          "\t(void) mig_strncpy(Mess.In.\(a.argMsgField), \(a.argVarName), \(t.itTypeSize));")
      } else {
        w.writeln("\tMess.In.\(a.argMsgField) = \(a.argVarName);")
      }
    }
    arg = a.argNext
  }

  // Send message
  w.writeln("\tmsg_result = mach_msg(&Mess.In.Head,")
  w.writeln("\t\tMACH_SEND_MSG|MACH_RCV_MSG|MACH_RCV_TIMEOUT,")
  w.writeln("\t\tMess.In.Head.msgh_size, sizeof(Mess.Out),")
  w.writeln("\t\tmsgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);")
  w.blankLine()

  w.writeln("\tif (msg_result != MACH_MSG_SUCCESS) {")
  w.writeln("\t\treturn msg_result;")
  w.writeln("\t}")
  w.blankLine()

  // Extract return code
  if akCheck(rt.rtRetCode?.argKind ?? 0, akbReply) {
    w.writeln("\tif (Mess.Out.Head.msgh_id != \(Global.subsystemBase + rt.rtNumber)) {")
    w.writeln("\t\treturn MIG_REPLY_MISMATCH;")
    w.writeln("\t}")
    w.writeln("\t\(rt.rtRetCode?.argName ?? "RetCode") = Mess.Out.RetCode;")
  }

  // Extract reply args
  arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbReturnRcv) && akCheck(a.argKind, akbReturnBody) {
      if let t = a.argType, t.itString {
        w.writeln(
          "\t(void) mig_strncpy(\(a.argVarName), Mess.Out.\(a.argMsgField), \(t.itTypeSize));")
      } else {
        w.writeln("\t*\(a.argVarName) = Mess.Out.\(a.argMsgField);")
      }
    }
    arg = a.argNext
  }

  w.writeln("\treturn KERN_SUCCESS;")
  w.writeln("}")
  w.blankLine()
}

private func writeUserSimpleRoutine(_ w: inout AccumWriter, rt: Routine) {
  let userName = Global.userPrefix.isEmpty ? rt.rtName : Global.userPrefix + rt.rtName
  let retType = returnTypeStr(rt)

  w.writeln("/* SimpleRoutine \(rt.rtName) */")
  w.write("mig_external \(retType) \(userName)\n(")

  var first = true
  var arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbUserArg) {
      if !first { w.write(",\n") }
      first = false
      let star = (a.argType?.itNativePointer ?? false) ? "*" : ""
      w.write("\t\(a.argType?.itUserType ?? "void") \(star)\(a.argVarName)")
    }
    arg = a.argNext
  }
  if first { w.write("\tvoid") }
  w.writeln(")")
  w.writeln("{")
  w.writeln("\t__Request__\(rt.rtName)_t In;")
  w.writeln("\tmach_msg_return_t msg_result;")
  w.blankLine()

  w.writeln("\t(void) memset(&In, 0, sizeof(In));")
  w.writeln("\tIn.Head.msgh_bits = MACH_MSGH_BITS(19, 0);")
  w.writeln("\tIn.Head.msgh_remote_port = \(rt.rtRequestPort?.argVarName ?? "MACH_PORT_NULL");")
  w.writeln("\tIn.Head.msgh_size = (mach_msg_size_t)sizeof(In);")
  w.writeln("\tIn.Head.msgh_id = \(Global.subsystemBase + rt.rtNumber);")

  // Fill args
  arg = rt.rtArgs
  while let a = arg {
    if akCheck(a.argKind, akbSendSnd) && akCheck(a.argKind, akbSendBody) {
      w.writeln("\tIn.\(a.argMsgField) = \(a.argVarName);")
    }
    arg = a.argNext
  }

  w.writeln(
    "\tmsg_result = mach_msg(&In.Head, MACH_SEND_MSG, In.Head.msgh_size, 0, MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);"
  )
  w.writeln("\treturn msg_result;")
  w.writeln("}")
  w.blankLine()
}
