module(
    name = "monorepo",
    version = "0.1.0",
)

bazel_dep(name = "rules_rs", version = "0.0.106")
git_override(
    module_name = "rules_rs",
    commit = "618daeaa8107ca86e1c4352409f2b395dabf7574",
    patch_strip = 1,
    patches = [
        "//third_party:patches/rules_rs_cargolock_v4.patch",
        "//third_party:patches/rules_rs_weak_dep_resolver.patch",
        "//third_party:patches/rules_rs_aarch64_none_linker.patch",
        "//third_party:patches/rules_rs_baremetal_no_default_features.patch",
    ],
    remote = "https://github.com/hermeticbuild/rules_rs.git",
)

bazel_dep(name = "llvm", version = "0.8.9")
git_override(
    module_name = "llvm",
    commit = "53fe78a34c96b736eb0033f6ade601d8352dc93c",
    remote = "https://github.com/hermeticbuild/hermetic-llvm.git",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_lib", version = "3.2.2")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_qemu", version = "0.3.0")
git_override(
    module_name = "rules_qemu",
    commit = "de0cdb392c5a4095528122a0725d48eec9c6befd",
    remote = "https://github.com/hermeticbuild/rules_qemu.git",
)

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "868c433f823d2d4eb7ce68198cd9d38bf75d61ae",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "mimalloc",
    build_file = "//third_party:mimalloc/mimalloc.BUILD.bazel",
    sha256 = "19a43af0645c57d348e729d5b31e23e912582911bb1047f795790834d3416221",
    strip_prefix = "mimalloc-3.5.0",
    urls = [
        "https://github.com/microsoft/mimalloc/archive/refs/tags/v3.5.0.tar.gz",
    ],
)

http_archive(
    name = "zlib-ng",
    build_file = "//third_party:zlib-ng/zlib.BUILD.bazel",
    sha256 = "661c30d260d37a4f04a0cbb3e8cae701e176f63dcad669ba5cb9ff1172fcf37e",
    strip_prefix = "zlib-ng-7cf22b9e19e08cf6719e48433681349c2a5f1d7e",
    urls = [
        "https://github.com/zlib-ng/zlib-ng/archive/7cf22b9e19e08cf6719e48433681349c2a5f1d7e.tar.gz",
    ],
)

toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
toolchains.toolchain(
    edition = "2024",
    version = "nightly/2026-08-18",
)
use_repo(toolchains, "default_rust_toolchains")

llvm = use_extension("@llvm//extensions:llvm.bzl", "llvm")
llvm.version(
    llvm_version = "23.1.0-rc1",
)
use_repo(llvm, "llvm-project")

osx = use_extension("@llvm//extensions:osx.bzl", "osx")
osx.frameworks(
    names = [
        "AppKit",
        "ApplicationServices",
        "CFNetwork",
        "Carbon",
        "ColorSync",
        "CoreFoundation",
        "CoreGraphics",
        "CoreImage",
        "CoreServices",
        "CoreText",
        "CoreVideo",
        "Foundation",
        "ImageIO",
        "IOKit",
        "Kernel",
        "Metal",
        "OSLog",
        "QuartzCore",
        "Security",
        "SystemConfiguration",
    ],
)

rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
rules_rust.patch(
    patches = [
        "//third_party:patches/rules_rust_flycheck_src_relpath.patch",
    ],
    strip = 1,
)
use_repo(rules_rust, "rules_rust")

xnu = use_extension("//extensions:xnu.bzl", "xnu")
use_repo(xnu, "xnu")

qemu = use_extension("@rules_qemu//qemu/extension:qemu.bzl", "qemu")
qemu.system_toolchain(
    system_target = "aarch64-softmmu",
    target_settings = ["//boot:qemu_system_target_aarch64"],
)
use_repo(
    qemu,
    "qemu_system_toolchains",
    "qemu_user_toolchains",
)

register_toolchains(
    "@default_rust_toolchains//...",
    "@llvm//toolchain:all",
    "@qemu_system_toolchains//:all",
    "@qemu_user_toolchains//:all",
)

crate = use_extension("@rules_rs//rs:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lock = "//third_party:Cargo.lock",
    cargo_toml = "//third_party:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-msvc",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-none",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
    ],
)
crate.annotation(
    crate = "cbindgen",
    gen_binaries = ["cbindgen"],
)
crate.annotation(
    crate = "spin",
    crate_features = [
        "mutex",
        "spin_mutex",
    ],
)
crate.annotation_select(
    crate = "scopeguard",
    crate_features = [],
    triples = ["aarch64-unknown-none"],
)

# crate.annotation(
#     crate = "ruffle_core",
#     patch_args = ["-p1"],
#     patches = [
#         "//third_party/ruffle:lib-rs-embedder-ui.patch",
#         "//third_party/ruffle:loader-run-first-frame-scripts.patch",
#         "//third_party/ruffle:movie_clip-run-first-frame-scripts.patch",
#         "//third_party/ruffle:playerglobal-paths.patch",
#     ],
#     strip_prefix = "core",
# )
crate.annotation(
    crate = "ruffle_common",
    strip_prefix = "core/common",
)
crate.annotation(
    crate = "ruffle_macros",
    strip_prefix = "core/macros",
)
crate.annotation(
    crate = "build_playerglobal",
    strip_prefix = "core/build_playerglobal",
)
crate.annotation(
    crate = "asc",
    strip_prefix = "tools/asc",
)
crate.annotation(
    crate = "flv-rs",
    strip_prefix = "flv",
)
crate.annotation(
    crate = "naga-agal",
    strip_prefix = "render/naga-agal",
)
crate.annotation(
    crate = "pixel_bender",
    strip_prefix = "render/pixel_bender",
)
crate.annotation(
    crate = "ruffle_render",
    strip_prefix = "render",
)
crate.annotation(
    crate = "ruffle_video",
    strip_prefix = "video",
)
crate.annotation(
    crate = "ruffle_wstr",
    strip_prefix = "wstr",
)

# crate.annotation(
#     crate = "swf",
#     patch_args = ["-p1"],
#     patches = [
#         "//third_party/ruffle:swf-as-writer.patch",
#     ],
#     strip_prefix = "swf",
# )
crate.annotation(
    crate = "flash-lso",
    strip_prefix = "flash-lso",
)
crate.annotation(
    crate = "h263-rs-yuv",
    strip_prefix = "yuv",
)
crate.annotation(
    crate = "gc-arena",
    strip_prefix = ".",
)
crate.annotation(
    crate = "gc-arena-derive",
    strip_prefix = "derive",
)
crate.annotation(
    crate = "zune-png",
    strip_prefix = "crates/zune-png",
)
crate.annotation(
    crate = "zune-core",
    strip_prefix = "crates/zune-core",
)
crate.annotation(
    crate = "zune-inflate",
    strip_prefix = "crates/zune-inflate",
)
use_repo(crate, "crates")
