"""Vendors apple-oss-distributions/xnu as a source-only repository.

Fetch runs xnu's SETUP/config tool to emit the authentic ARM64/VMAPPLE
DEVELOPMENT file list and generated feature-option headers. Compilation,
assym generation, and MIG (`//migcom`) live in `//xnu`, not in this fetch.
"""

load("//extensions/private:config_tool.bzl", "build_config_tool")
load("//extensions/private:sysconf.bzl", "extract_defines", "extract_var", "gen_sysconf_and_run", "normalize")

def _starlark_list(values):
    return "[\n" + "".join(["    %r,\n" % v for v in values]) + "]"

ALL_SUBSYSTEMS = [
    "osfmk",
    "bsd",
    "pexpert",
    "iokit",
    "libkern",
    "libsa",
    "san",
    "security",
]

def _xnu_kernel_source_impl(ctx):
    ctx.download_and_extract(
        url = ctx.attr.url,
        sha256 = ctx.attr.sha256,
        stripPrefix = ctx.attr.strip_prefix,
        type = "tar.gz",
    )

    # EXTERNAL_HEADERS lacks the TrustCache client library headers Apple omits
    # from the public xnu drop (osfmk/vm/pmap_cs.h -> bsd/sys/code_signing.h ->
    # <TrustCache/API.h>); the four headers this patch adds are pure vendored
    # additions (from Apple's own published sources, no xnu source is touched)
    # matching what a real macOS SDK provides alongside xnu.
    ctx.patch(ctx.attr._trustcache_patch, strip = 1)

    python3 = ctx.which("python3") or ctx.which("python")
    if not python3:
        fail("xnu_kernel_source requires python3 on PATH")
    resolver = ctx.path(ctx.attr._resolver)

    config_bin = build_config_tool(ctx)

    root_abs = str(ctx.path("."))
    srcs = {}
    defines = {}
    for subsys in ALL_SUBSYSTEMS:
        objectdir_abs = root_abs + "/generated/" + subsys
        makefile_text = gen_sysconf_and_run(ctx, python3, resolver, config_bin, subsys, objectdir_abs)
        cfiles = extract_var(makefile_text, "CFILES")
        sfiles = extract_var(makefile_text, "SFILES")
        cxxfiles = extract_var(makefile_text, "CXXFILES")
        all_files = normalize(subsys, cfiles + sfiles + cxxfiles)

        # keep only files that actually exist (defensive: config's file
        # lists include a small number of entries gated on options our
        # bounded resolver may not model identically to Apple's device map).
        existing = []
        for f in all_files:
            if ctx.path(f).exists:
                existing.append(f)
        srcs[subsys] = sorted(existing)
        defines[subsys] = extract_defines(makefile_text)

    # Real Apple builds flatten each COMPONENT's public headers into a
    # shared EXPORT_HDRS tree via `make exporthdrs` (makedefs/MakeInc.def:78
    # lists san as a COMPONENT); e.g. `#include <san/kasan.h>` resolves to
    # san/memory/kasan.h post-export. We don't run the full exporthdrs
    # machinery, just generate the same flattening as tiny forwarding shims.
    san_files = ctx.execute(["find", "san", "-name", "*.h"]).stdout.splitlines()
    seen = {}
    for path in san_files:
        path = path.strip()
        if not path:
            continue
        name = path.split("/")[-1]
        if name in seen:
            continue
        seen[name] = path
        ctx.file("san_export/san/" + name, "#include \"" + path + "\"\n")

    def split_asm(files):
        c = [f for f in files if not f.endswith(".s")]
        s = [f for f in files if f.endswith(".s")]
        return c, s

    bzl_lines = ["# Generated by //extensions:xnu.bzl - do not edit."]
    for subsys in ALL_SUBSYSTEMS:
        c, s = split_asm(srcs[subsys])
        tag = subsys.upper()
        bzl_lines.append("%s_C_SRCS = %s" % (tag, _starlark_list(c)))
        bzl_lines.append("%s_S_SRCS = %s" % (tag, _starlark_list(s)))
        bzl_lines.append("%s_DEFINES = %s" % (tag, _starlark_list(defines[subsys])))

    ctx.file("xnu_srcs.bzl", "\n".join(bzl_lines) + "\n")
    ctx.file("BUILD.bazel", ctx.read(ctx.path(ctx.attr._build_template)))
    ctx.file("MODULE.bazel", "module(name = \"xnu\", version = \"0.0.0\")\nbazel_dep(name = \"rules_cc\", version = \"0.2.22\")\n")

xnu_kernel_source = repository_rule(
    implementation = _xnu_kernel_source_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "strip_prefix": attr.string(mandatory = True),
        "_resolver": attr.label(
            default = Label("//tools/xnu_config:resolve_options.py"),
            allow_single_file = True,
        ),
        "_trustcache_patch": attr.label(
            default = Label("//tools/xnu_config:TrustCache.patch"),
            allow_single_file = True,
        ),
        "_build_template": attr.label(
            default = Label("//extensions/templates:BUILD.xnu.tpl"),
            allow_single_file = True,
        ),
    },
)

def _xnu_impl(module_ctx):
    xnu_kernel_source(
        name = "xnu",
        url = "https://codeload.github.com/apple-oss-distributions/xnu/tar.gz/ac9718fb1af618d5ce8678d0dc6e8a58f252216f",
        sha256 = "577f4a220304296332e28c802779e7b5e6a27a46812315aacf61c0269a03e12a",
        strip_prefix = "xnu-ac9718fb1af618d5ce8678d0dc6e8a58f252216f",
    )
    return module_ctx.extension_metadata(reproducible = True)

xnu = module_extension(implementation = _xnu_impl)
