# Generated by //extensions:xnu.bzl - source-only repo; compile in //xnu.
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

exports_files(glob(["**"], allow_empty = True))

filegroup(
    name = "security_headers",
    srcs = glob(["security/**/*.h"], allow_empty = True),
)
filegroup(
    name = "san_headers",
    srcs = glob(["san/**/*.h"], allow_empty = True),
)
filegroup(
    name = "san_export_headers",
    srcs = glob(["san_export/**/*.h"], allow_empty = True),
)
filegroup(
    name = "external_headers",
    srcs = glob(["EXTERNAL_HEADERS/**"], allow_empty = True),
)
filegroup(
    name = "bsd_headers",
    srcs = glob(["bsd/**/*.h"], allow_empty = True),
)
filegroup(
    name = "osfmk_headers",
    srcs = glob(["osfmk/**/*.h"], allow_empty = True),
)
filegroup(
    name = "osfmk_defs",
    srcs = glob(["osfmk/**/*.defs"], allow_empty = True),
)
filegroup(
    name = "iokit_headers",
    srcs = glob(["iokit/**/*.h"], allow_empty = True),
)
filegroup(
    name = "libkern_headers",
    srcs = glob(["libkern/**/*.h"], allow_empty = True),
)
filegroup(
    name = "libsa_headers",
    srcs = glob(["libsa/**/*.h"], allow_empty = True),
)
filegroup(
    name = "pexpert_headers",
    srcs = glob(["pexpert/**/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_osfmk",
    srcs = glob(["generated/osfmk/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_bsd",
    srcs = glob(["generated/bsd/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_pexpert",
    srcs = glob(["generated/pexpert/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_iokit",
    srcs = glob(["generated/iokit/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_libkern",
    srcs = glob(["generated/libkern/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_libsa",
    srcs = glob(["generated/libsa/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_san",
    srcs = glob(["generated/san/*.h"], allow_empty = True),
)
filegroup(
    name = "config_headers_security",
    srcs = glob(["generated/security/*.h"], allow_empty = True),
)

# Header-only so dependents in //xnu get -Iexternal/.../xnu/{osfmk,...}.
cc_library(
    name = "kernel_headers",
    hdrs = [
        ":osfmk_headers",
        ":bsd_headers",
        ":pexpert_headers",
        ":external_headers",
        ":libkern_headers",
        ":libsa_headers",
        ":iokit_headers",
        ":security_headers",
        ":san_headers",
        ":san_export_headers",
        ":config_headers_osfmk",
        ":config_headers_bsd",
        ":config_headers_pexpert",
        ":config_headers_iokit",
        ":config_headers_libkern",
        ":config_headers_libsa",
        ":config_headers_san",
        ":config_headers_security",
    ],
    includes = [
        ".",
        "EXTERNAL_HEADERS",
        "osfmk",
        "bsd",
        "iokit",
        "libkern",
        "libsa",
        "osfmk/libsa",
        "pexpert",
        "security",
        "san",
        "generated/osfmk",
        "generated/bsd",
        "generated/pexpert",
        "generated/iokit",
        "generated/libkern",
        "generated/libsa",
        "generated/san",
        "generated/security",
        "san_export",
    ],
)
